#!/bin/bash

# Make sure we have root permissions before we begin
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Download public certificate and additionally add it as a trusted ca in global known hosts
curl -s https://raw.githubusercontent.com/ahoeppner/setup-utilities/main/files/ca.pub > /etc/ssh/ca.pub
echo @cert-authority *.servers.hwlocal.net $(cat /etc/ssh/ca.pub) > /etc/ssh/ssh_known_hosts
echo 'Public CA added...'

# Download modified sshd_config
curl -s https://raw.githubusercontent.com/ahoeppner/setup-utilities/main/files/sshd_config > /etc/ssh/sshd_config
echo 'sshd_config updated...'

# Copy the rsa public key to ssh-ca for signing
cd /etc/ssh
echo "Copying rsa public key to ssh-ca for signing..."
scp -q /etc/ssh/ssh_host_rsa_key.pub helper@ssh-ca.servers.hwlocal.net:/home/helper/$HOSTNAME.pub
echo -e "\nlog onto CA and sign key, then return here to retrieve it with by pressing [ENTER]..."
read  # this command waits for a newline character before proceeding

# wait for user input and then pull cert back
scp -q helper@ssh-ca.servers.hwlocal.net:/home/helper/$HOSTNAME-cert.pub /etc/ssh/ssh_host_rsa_key-cert.pub

# Restart SSHD to pull in new config
echo "Restarting SSHD..."
systemctl restart sshd

echo -e "Done! Your fresh certificate reads:\n"
ssh-keygen -Lf /etc/ssh/ssh_host_rsa_key-cert.pub
